#!/usr/bin/env bash
# Generated by doom-stitcher on 2026-06-07
# Idempotent first-time Doom Emacs installer for this DOOMDIR.
set -euo pipefail

DOOMDIR="${DOOMDIR:-$HOME/.config/doom}"
EMACSDIR="${EMACSDIR:-$HOME/.config/emacs}"
DOOM_REPO="https://github.com/doomemacs/doomemacs"


# 2. Clone Doom Emacs (shallow)
if [ ! -d "$EMACSDIR" ]; then
  echo "Cloning Doom Emacs to $EMACSDIR ..."
  git clone --depth 1 "$DOOM_REPO" "$EMACSDIR"
fi

# 3. Install / sync
if [ ! -x "$EMACSDIR/bin/doom" ]; then
  echo "Running doom install ..."
  "$EMACSDIR/bin/doom" install --no-config
fi

echo "Running doom sync ..."
"$EMACSDIR/bin/doom" sync

cat <<'NOTE'

✅ Doom Emacs installed. Launch with:
    ~/.config/emacs/bin/doom emacs

Run `~/.config/emacs/bin/doom doctor` if anything looks wrong.
NOTE
