"""Org-mode minimal parser for tangle-aware blocks.

~/.config/doom/workflow/utils/org.py
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_BEGIN_SRC = re.compile(
    r"""^\#\+BEGIN_SRC\s+(?P<lang>[\w-]+)?\s*(?::[ \t]*(?P<header>.*?))?$""",
    re.MULTILINE | re.IGNORECASE,
)
_END_SRC = re.compile(r"^\#\+END_SRC\s*$", re.MULTILINE | re.IGNORECASE)


@dataclass
class SrcBlock:
    lang: str
    headers: dict[str, str]
    body: str
    start_line: int
    end_line: int

    @property
    def tangle(self) -> str:
        """Resolved tangle target. Defaults to 'config.el' (Doom literate default)."""
        return self.headers.get("tangle", "config.el").strip()

    def with_default_tangle(self, default: str = "config.el") -> "SrcBlock":
        if "tangle" not in self.headers:
            new_headers = dict(self.headers)
            new_headers["tangle"] = default
            return SrcBlock(
                self.lang, new_headers, self.body, self.start_line, self.end_line
            )
        return self


def extract_src_blocks(org_text: str) -> list[SrcBlock]:
    """Find all `#+begin_src ... #+end_src` blocks in an org file."""
    out: list[SrcBlock] = []
    for m in _BEGIN_SRC.finditer(org_text):
        lang = m.group("lang") or ""
        header_str = m.group("header") or ""
        headers = _parse_header_args(header_str)
        start = m.end()
        end_m = _END_SRC.search(org_text, pos=start)
        if not end_m:
            continue
        body = org_text[start : end_m.start()]
        out.append(
            SrcBlock(
                lang=lang,
                headers=headers,
                body=body,
                start_line=org_text[: m.start()].count("\n") + 1,
                end_line=org_text[: end_m.end()].count("\n") + 1,
            )
        )
    return out


def _parse_header_args(s: str) -> dict[str, str]:
    """Parse the header-args string after `#+begin_src LANG`.

    Format: `:key1 val1 :key2 val2 :flag`.
    """
    out: dict[str, str] = {}
    tokens = s.split()
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok.startswith(":"):
            key = tok[1:]
            if i + 1 < len(tokens) and not tokens[i + 1].startswith(":"):
                out[key] = tokens[i + 1]
                i += 2
            else:
                out[key] = "yes"
                i += 1
        else:
            i += 1
    return out


def parse_property_drawer(org_text: str) -> dict[str, str]:
    """Read the top-of-file #+PROPERTY: lines (case-insensitive directive)."""
    out: dict[str, str] = {}
    for line in org_text.splitlines():
        if line[:11].upper() == "#+PROPERTY:":
            rest = line[len("#+PROPERTY:") :].strip()
            if ":" in rest:
                key, val = rest.split(":", 1)
                out[key.strip()] = val.strip()
        elif line.startswith("#+") or line.strip() == "":
            continue
        else:
            break
    return out


def render_config_org(
    *,
    title: str,
    preamble: str,
    init_el: str,
    packages_el: str,
    config_el: str,
    headings: list[tuple[str, str]] | None = None,
) -> str:
    """Render the final literate config.org.

    `headings` is an optional list of (heading, body) pairs to add
    between the preamble and the tangle blocks, providing documentation
    around the generated code.
    """
    parts: list[str] = []
    parts.append(f"#+title: {title}")
    parts.append(f"#+subtitle: Generated by doom-stitcher on {preamble}")
    parts.append("#+startup: overview")
    parts.append("#+property: header-args:emacs-lisp :results none :lexical t")
    parts.append("")

    if headings:
        for h, b in headings:
            parts.append(f"* {h}")
            parts.append("")
            parts.append(b)
            parts.append("")

    # init.el block
    parts.append("* Init")
    parts.append("")
    parts.append("The ~doom!~ block and any pre-modules init code. This block is")
    parts.append("tangled to =init.el= and loaded very early by Doom.")
    parts.append("")
    parts.append("#+begin_src emacs-lisp :tangle init.el")
    parts.append(init_el.rstrip())
    parts.append("#+end_src")
    parts.append("")

    # packages.el block
    parts.append("* Packages")
    parts.append("")
    parts.append(
        "Package declarations. This block is tangled to =packages.el= and read"
    )
    parts.append("by Doom's package manager (~straight.el~).")
    parts.append("")
    parts.append("#+begin_src emacs-lisp :tangle packages.el")
    parts.append(packages_el.rstrip())
    parts.append("#+end_src")
    parts.append("")

    # config.el block
    parts.append("* Configuration")
    parts.append("")
    parts.append("User configuration. This block is tangled to =config.el= and loaded")
    parts.append("after all Doom modules have been initialized.")
    parts.append("")
    parts.append("#+begin_src emacs-lisp :tangle config.el")
    parts.append(config_el.rstrip())
    parts.append("#+end_src")
    parts.append("")

    return "\n".join(parts) + "\n"
